version: '3.1'

services:
  db:
    container_name: db_mysql_server
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'vital_signs'
      MYSQL_ROOT_PASSWORD: 'alsharif_2022'
    networks:
      - my-network

  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    links:
      - db
    depends_on:
      - db
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: